"""Create initial tables

Revision ID: 4b3f1f39bce1
Revises: 
Create Date: 2022-12-26 20:46:45.460694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b3f1f39bce1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    op.create_table(
        "points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("is_classroom", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_points_id"), "points", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("login", sa.String(length=80), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "edges",
        sa.Column("from_point_id", sa.Integer(), nullable=False),
        sa.Column("to_point_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_point_id"],
            ["points.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_point_id"],
            ["points.id"],
        ),
        sa.PrimaryKeyConstraint("from_point_id", "to_point_id"),
    )
    op.create_table(
        "floors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("map_image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["map_image_id"],
            ["images.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_floors_id"), "floors", ["id"], unique=False)
    op.create_table(
        "floor_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("floor_id", sa.Integer(), nullable=True),
        sa.Column("point_id", sa.Integer(), nullable=True),
        sa.Column("x", sa.Integer(), nullable=True),
        sa.Column("y", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["floor_id"],
            ["floors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["points.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("floor_id", "point_id"),
    )
    op.create_index(op.f("ix_floor_points_id"), "floor_points", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_floor_points_id"), table_name="floor_points")
    op.drop_table("floor_points")
    op.drop_index(op.f("ix_floors_id"), table_name="floors")
    op.drop_table("floors")
    op.drop_table("edges")
    op.drop_table("users")
    op.drop_index(op.f("ix_points_id"), table_name="points")
    op.drop_table("points")
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
